Update Ksun+BB+SUSFS.yml

diff --git a/.github/workflows/Ksun+BB+SUSFS.yml b/.github/workflows/Ksun+BB+SUSFS.yml
--- a/.github/workflows/Ksun+BB+SUSFS.yml
+++ b/.github/workflows/Ksun+BB+SUSFS.yml
@@ -10,65 +10,37 @@ jobs:
   build:
     name: Build Kernel by ${{ github.actor }}
     runs-on: ubuntu-latest
+
     env:
       CLANG_VERSION: clang-r547379
       GCC_TAG: android-12.1.0_r27
       Lineage_VERSION: lineage-23.2
 
     steps:
-    - uses: actions/checkout@v6
-    
+    - uses: actions/checkout@v4
+
     - name: Set swap to 10G
       uses: pierotofy/set-swap-space@master
       with:
         swap-size-gb: 10
-    
-    - name: Setup build kernel environment
+
+    - name: Setup build environment
       run: |
         echo "BUILD_TIME=$(TZ=Asia/Kolkata date "+%y%m%d")" >> $GITHUB_ENV
         echo "BUILD_TIME_1=$(TZ=Asia/Kolkata date "+%Y-%m-%d")" >> $GITHUB_ENV
         sudo apt-get update
-        sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib bzip2 libbz2-dev liblz4-tool make squashfs-tools dpkg-dev libssl-dev python3 bc libc6-dev-i386 libncurses5-dev
+        sudo apt-get install -y git ccache automake flex lzop bison gperf build-essential zip curl \
+          zlib1g-dev g++-multilib bzip2 libbz2-dev liblz4-tool make squashfs-tools \
+          dpkg-dev libssl-dev python3 bc libc6-dev-i386 libncurses5-dev
         mkdir -p $GITHUB_WORKSPACE/kernel_workspace
 
-    - name: Cache Clang toolchain
-      id: cache-clang
-      uses: actions/cache@v5
-      with:
-        path: ${{ github.workspace }}/kernel_workspace/clang-aosp
-        key: ${{ env.CLANG_VERSION }}
-
-    - name: Download & extract Clang-aosp
-      if: steps.cache-clang.outputs.cache-hit != 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        mkdir -p clang-aosp
-        wget -O ${CLANG_VERSION}.tar.gz \
-          https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/${CLANG_VERSION}.tar.gz
-        tar -C clang-aosp -zxvf ${CLANG_VERSION}.tar.gz
-
-    - name: Cache GCC toolchain
-      id: cache-gcc
-      uses: actions/cache@v4
-      with:
-        path: ${{ github.workspace }}/kernel_workspace/gcc-64
-        key: gcc-aarch64-${{ env.GCC_TAG }}
-
-    - name: Download & extract Gcc-aosp
-      if: steps.cache-gcc.outputs.cache-hit != 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        mkdir -p gcc-64
-        wget -O gcc-aarch64.tar.gz \
-          https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/${GCC_TAG}.tar.gz
-        tar -C gcc-64 -zxvf gcc-aarch64.tar.gz
-    
     - name: Download kernel source
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        git clone --recursive https://github.com/LineageOS/android_kernel_oneplus_sm8250 -b ${{ env.Lineage_VERSION }} android-kernel --depth=1
+        git clone --recursive https://github.com/LineageOS/android_kernel_oneplus_sm8250 \
+          -b ${{ env.Lineage_VERSION }} android-kernel --depth=1
 
-    - name: Set up KSUN
+    - name: Setup KSUN + SUSFS
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
         curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy
@@ -77,108 +49,64 @@ jobs:
         bash $GITHUB_WORKSPACE/patches/kernel-4.19_5.4-patch.sh
         bash $GITHUB_WORKSPACE/patches/syacall_hook.sh
         bash $GITHUB_WORKSPACE/patches/backport_patch.sh
-      
-        #git apply --reject --whitespace=fix $GITHUB_WORKSPACE/patches/patch2.patch
 
-    - name: Apply patch
+    - name: Apply SUSFS patch
       run: |
-              set +e
-              git apply --reject --whitespace=fix $GITHUB_WORKSPACE/patches/patch2.patch
-              echo "Exit code: $?"
-              find . -name "*.rej"
-              set -e
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+        set +e
+        git apply --reject --whitespace=fix $GITHUB_WORKSPACE/patches/patch2.patch
+        echo "Exit code: $?"
+        find . -name "*.rej"
+        set -e
 
     - name: Upload reject files
       if: always()
       uses: actions/upload-artifact@v4
       with:
         name: patch-reject-files
-        path: |
-               **/*.rej
-    
-        
-        # bash $GITHUB_WORKSPACE/patches/susfs_fix.sh
-        echo "CONFIG_KSU_MANUAL_HOOK=y
-              CONFIG_KSU_SUSFS=y
-              CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
-              CONFIG_KSU_SUSFS_SUS_PATH=y
-              CONFIG_KSU_SUSFS_SUS_MOUNT=y
-              CONFIG_KSU_SUSFS_SUS_KSTAT=y
-              CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y
-              CONFIG_KSU_SUSFS_TRY_UMOUNT=y
-              CONFIG_KSU_SUSFS_SPOOF_UNAME=y
-              CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
-              CONFIG_KSU_SUSFS_ENABLE_LOG=y
-              CONFIG_KSU_SUSFS_SUS_SU=y" >> arch/arm64/configs/vendor/kona-perf_defconfig
+        path: kernel_workspace/android-kernel/**/*.rej
 
-        echo "[+] Enabling SUSFS configs in defconfig"
+    - name: Enable SUSFS configs
+      run: |
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+        cat <<EOF >> arch/arm64/configs/vendor/kona-perf_defconfig
+           CONFIG_KSU_MANUAL_HOOK=y
+           CONFIG_KSU_SUSFS=y
+           CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
+           CONFIG_KSU_SUSFS_SUS_PATH=y
+           CONFIG_KSU_SUSFS_SUS_MOUNT=y
+           CONFIG_KSU_SUSFS_SUS_KSTAT=y
+           CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y
+           CONFIG_KSU_SUSFS_TRY_UMOUNT=y
+           CONFIG_KSU_SUSFS_SPOOF_UNAME=y
+           CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
+           CONFIG_KSU_SUSFS_ENABLE_LOG=y
+           CONFIG_KSU_SUSFS_SUS_SU=y
+        EOF
+        echo "[✓] SUSFS configs enabled"
 
-        echo "======================================"
-        echo "[✓] KernelSU + SUSFS integration DONE"
-        echo "======================================"
-
-        
-        KSU_VERSION=$(cd KernelSU-Next && expr $(/usr/bin/git rev-list --count HEAD) + 30000)
-        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-        cd scripts
-        sed -i 's/ -dirty//g' setlocalversion
-    
-    - name: Build kernel with KSUN
+    - name: Build kernel
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
         export ARCH=arm64
         export SUBARCH=arm64
-        export BRAND_SHOW_FLAG=oneplus
-        
-        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc-64/bin:$PATH
-        export KBUILD_BUILD_HOST=Github-Action
-        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
-        BA_CMD="CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android-"
-        EX_CMD="LD=ld.lld LLVM=1 LLVM_IAS=1"
-        DEFCONFIG="vendor/kona-perf_defconfig vendor/debugfs.config vendor/oplus.config"
-        make O=out ARCH=arm64 CC=clang $BA_CMD $EX_CMD $DEFCONFIG
-        make -j$(nproc --all) O=out ARCH=arm64 CC=clang $BA_CMD $EX_CMD
-    
-    - name: Check a kernel output files with rsuntk KernelSU
+        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
+        make O=out ARCH=arm64 CC=clang vendor/kona-perf_defconfig
+        make -j$(nproc) O=out ARCH=arm64 CC=clang
+
+    - name: Check kernel output
       run: |
-       cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out
-       if [ -f arch/arm64/boot/Image ]; then
-           echo "CHECK_IMAGE=true" >> $GITHUB_ENV
-           KERNEL_VERSION=$(cat include/config/kernel.release)
-           echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
-       else
-           echo "Kernel output file is empty"
-           exit 1
-       fi
-      
-    - name: Make AnyKernel3 with KSUN
-      if: ${{ env.CHECK_IMAGE == 'true' }}
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
-        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
-        sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
-        sed -i 's/IS_SLOT_DEVICE=0;/IS_SLOT_DEVICE=auto;/g' AnyKernel3/anykernel.sh
-        cp android-kernel/out/arch/arm64/boot/Image AnyKernel3/
-        rm -rf AnyKernel3/.git* AnyKernel3/README.md
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out
+        if [ -f arch/arm64/boot/Image ]; then
+          echo "CHECK_IMAGE=true" >> $GITHUB_ENV
+        else
+          echo "Kernel build failed"
+          exit 1
+        fi
 
     - name: Upload Image
       if: ${{ env.CHECK_IMAGE == 'true' }}
-      uses: actions/upload-artifact@v6
+      uses: actions/upload-artifact@v4
       with:
         name: Image
         path: kernel_workspace/android-kernel/out/arch/arm64/boot/Image
-
-    - name: Upload AnyKernel3
-      if: ${{ env.CHECK_IMAGE == 'true' }}
-      uses: actions/upload-artifact@v6
-      with:
-        name: AK3-${{ env.Lineage_VERSION }}-OPlus-SM8250-KSU_${{ env.KSUVER }}-${{ env.BUILD_TIME }}
-        path: kernel_workspace/AnyKernel3/*
-    
-    - name: Zip files
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/arch/arm64/boot
-        zip $GITHUB_WORKSPACE/Image.zip Image
-        cd $GITHUB_WORKSPACE/kernel_workspace/AnyKernel3
-        zip -r $GITHUB_WORKSPACE/AK3-${{ env.Lineage_VERSION }}-OPlus-SM8250-KSU_${{ env.KSUVER }}-${{ env.BUILD_TIME }}.zip ./*
